from math import pi,cos,sin
############################################################
## ROBOT CONSTANTS
############################################################
ROBOT_SPHERE_RADIUS = 0.3 #the max sphere embedded in the irreducible volume
ROBOT_MAX_SLOPE = 5 # in degrees
ROBOT_FOOT_RADIUS = 0.15 # in m
ROBOT_FOOT_HEIGHT = 0.09 # in m
ROBOT_VOLUME_MIN_HEIGHT = 1.2 #in m
ROBOT_VOLUME_MAX_HEIGHT = 1.539 #in m
ROBOT_HEAD_SIZE = 0.21 #in m

#ROBOT_DIST_FOOT_SOLE = 0.09
#ROBOT_DIST_KNEE_FOOT = 0.31
#ROBOT_DIST_HIP_KNEE = 0.31
#ROBOT_DIST_WAIST_HIP = 0.38
#ROBOT_DIST_NECK_WAIST = 0.31
#ROBOT_DIST_HEAD_NECK = 0.21
ROBOT_DIST_FOOT_SOLE = 0.09
ROBOT_DIST_KNEE_FOOT = 0.31
ROBOT_DIST_HIP_KNEE = 0.31
ROBOT_DIST_WAIST_HIP = 0.28
ROBOT_DIST_NECK_WAIST = 0.41
ROBOT_DIST_HEAD_NECK = 0.21

ROBOT_APERTURE_KNEE_FOOT= pi/3
ROBOT_APERTURE_HIP_FOOT= pi/100
ROBOT_APERTURE_HIP_KNEE = pi/2.2
ROBOT_APERTURE_WAIST_HIP = pi/16
ROBOT_APERTURE_NECK_WAIST = pi/16
ROBOT_APERTURE_HEAD_NECK = pi/16

ROBOT_THICKNESS_FOOT_SOLE = 0.234
ROBOT_THICKNESS_KNEE_FOOT = 0.14
ROBOT_THICKNESS_HIP_KNEE = 0.10
ROBOT_THICKNESS_WAIST_HIP = 0.28
ROBOT_THICKNESS_NECK_WAIST = 0.34
ROBOT_THICKNESS_HEAD_NECK = 0.21

ROBOT_DIST_KNEE_FOOT_MIN = ROBOT_DIST_KNEE_FOOT*(cos(ROBOT_APERTURE_KNEE_FOOT))
ROBOT_DIST_HIP_FOOT_MIN = ROBOT_DIST_KNEE_FOOT_MIN+ROBOT_DIST_HIP_KNEE*(cos(ROBOT_APERTURE_HIP_KNEE))
ROBOT_DIST_WAIST_FOOT_MIN = ROBOT_DIST_HIP_FOOT_MIN+ROBOT_DIST_WAIST_HIP*(cos(ROBOT_APERTURE_WAIST_HIP))
ROBOT_DIST_NECK_FOOT_MIN = ROBOT_DIST_WAIST_FOOT_MIN+ROBOT_DIST_NECK_WAIST*(cos(ROBOT_APERTURE_NECK_WAIST))
ROBOT_DIST_HEAD_FOOT_MIN = ROBOT_DIST_NECK_FOOT_MIN+ROBOT_DIST_HEAD_NECK*(cos(ROBOT_APERTURE_HEAD_NECK))

ROBOT_DIST_KNEE_FOOT_MAX = ROBOT_DIST_KNEE_FOOT
ROBOT_DIST_HIP_FOOT_MAX = ROBOT_DIST_KNEE_FOOT_MAX+ROBOT_DIST_HIP_KNEE
ROBOT_DIST_WAIST_FOOT_MAX=ROBOT_DIST_HIP_FOOT_MAX+ROBOT_DIST_WAIST_HIP
ROBOT_DIST_NECK_FOOT_MAX =ROBOT_DIST_WAIST_FOOT_MAX+ROBOT_DIST_NECK_WAIST
ROBOT_DIST_HEAD_FOOT_MAX =ROBOT_DIST_NECK_FOOT_MAX+ROBOT_DIST_HEAD_NECK

ROBOT_DIST_HEAD_FOOT_MAX = 1.539

VSTACK_DELTA = ROBOT_VOLUME_MAX_HEIGHT/32
ROBOT_MAX_UPPER_BODY_DISTANCE_FROM_FOOT = sin(ROBOT_APERTURE_KNEE_FOOT)*ROBOT_DIST_KNEE_FOOT
############################################################
## PATH CONSTANTS
############################################################

PATH_DIST_WAYPOINTS_MAX = 0.2
PATH_RADIUS_START_REGION = 0.1
PATH_RADIUS_GOAL_REGION = 0.1
